"""initial schema

Revision ID: 8a0f62730212
Revises: 
Create Date: 2026-07-23 13:36:05.186649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0f62730212'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_channel_id')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commenters_min', sa.Integer(), nullable=False),
    sa.Column('commenters_max', sa.Integer(), nullable=False),
    sa.Column('delay_min_seconds', sa.Integer(), nullable=False),
    sa.Column('delay_max_seconds', sa.Integer(), nullable=False),
    sa.Column('content_filter_enabled', sa.Boolean(), nullable=False),
    sa.Column('stop_terms', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('session_string_enc', sa.Text(), nullable=False),
    sa.Column('proxy_type', sa.String(length=20), nullable=True),
    sa.Column('proxy_host', sa.String(length=255), nullable=True),
    sa.Column('proxy_port', sa.Integer(), nullable=True),
    sa.Column('proxy_username', sa.String(length=255), nullable=True),
    sa.Column('proxy_password_enc', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('daily_comment_cap', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LIMITED', 'BANNED', 'DISABLED', name='accountstatus'), nullable=False),
    sa.Column('status_note', sa.String(length=500), nullable=True),
    sa.Column('limited_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_channel_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'channel_id', name='uq_account_channel')
    )
    op.create_table('comment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('source_post_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_message_id', sa.BigInteger(), nullable=True),
    sa.Column('persona_name', sa.String(length=100), nullable=True),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('signature_text', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'POSTED', 'SKIPPED_FILTER', 'FAILED', name='commentstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_logs')
    op.drop_table('account_channel_assignments')
    op.drop_table('accounts')
    op.drop_table('personas')
    op.drop_table('global_settings')
    op.drop_table('channels')
    # ### end Alembic commands ###
