"""add channel invite link

Revision ID: d9d01acf87e9
Revises: 8a0f62730212
Create Date: 2026-07-23 23:56:04.277264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d01acf87e9'
down_revision: Union[str, Sequence[str], None] = '8a0f62730212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('invite_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'invite_link')
    # ### end Alembic commands ###
